# Generated by Django 5.2.1 on 2025-05-14 03:24

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('ticker', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('is_sp500', models.BooleanField(default=False)),
                ('current_price', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'user_id'], name='analytics_t_ticker_5c35b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('ticker', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('transaction_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('transaction_type', models.CharField(max_length=200)),
                ('transaction_price', models.FloatField(default=0.0)),
                ('transaction_quantity', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('future', models.CharField(max_length=1000)),
                ('strategy', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'transaction_id'], name='analytics_t_ticker_4ceda5_idx')],
            },
        ),
    ]
